Make app translatable
rajkumaar23/badgie pull request #12
Opened 2020-05-30 17:24 UTC by NathanBnm

2020-05-30 17:25 UTC, NathanBnm commented
This will close #10

2020-05-31 11:40 UTC, rajkumaar23 requested changes

2020-05-31 11:40 UTC, rajkumaar23 commented on po/com.github.rajkumaar23.badgie.pot
> +# SOME DESCRIPTIVE TITLE.
Can this be a more appropriate title ?

2020-05-31 11:40 UTC, rajkumaar23 commented on po/extra/extra.pot
> +# SOME DESCRIPTIVE TITLE.
And here too..

2020-06-01 07:51 UTC, NathanBnm commented
@rajkumaar23 these are auto-generated files, when adding languages the appropriate header will be generated automatically. For example in French it will be:

```
# French translations for com.github.rajkumaar23.badgie package.
# Copyright (C) 2020 THE com.github.rajkumaar23.badgieS COPYRIGHT HOLDER
# This file is distributed under the same license as the com.github.rajkumaar23.badgie package.
# Nathan Bonnemains (@NathanBnm), 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: com.github.rajkumaar23.badgie\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-06-15 09:50+0100\n"
"PO-Revision-Date: 2020-06-15 09:50+0100\n"
"Last-Translator: Nathan Bonnemains (@NathanBnm)\n"
"Language-Team: Français\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
```

2020-06-01 07:54 UTC, NathanBnm commented
Translation files are auto-generated by running

```
ninja com.github.rajkumaar23.badgie-update-po
```

for main translation and

```
ninja extra-update-po
```

for metadata translation

The `.pot` file is just a template file used by the generator to create the appropriate `.po` translation  file for each language code added in the `LINGUAS` file.

2020-06-01 08:05 UTC, rajkumaar23 commented
> Translation files are auto-generated by running
> 
> ```
> ninja com.github.rajkumaar23.badgie-update-po
> ```
> 
> for main translation and
> 
> ```
> ninja extra-update-po
> ```
> 
> for metadata translation
> 
> The `.pot` file is just a template file used by the generator to create the appropriate `.po` translation file for each language code added in the `LINGUAS` file.

Okay got it 👍🏼

2020-06-01 08:05 UTC, rajkumaar23 approved these changes

2020-06-01 08:06 UTC, merged